nelmio_cors:
  defaults:
    allow_credentials: false
    max_age: 600
    allow_headers: ['Content-Type', 'X-Api-Key']
    allow_methods: ['POST', 'OPTIONS']

  paths:
    '^/api/':
      allow_origin: ['http://127.0.0.1:8081'] 
      allow_methods: ['POST', 'OPTIONS']
